export default [
    {
    ID: '1',
    nombre: 'Jose',
    tipo: '3D',
    peso: 9,
    tamanoAnillo: '8U',
    tamanoPiedra: '1.3mm',
    material: 'oro',
    modelo: '<img src="">',
    detalle: 'no tan ancho',
    informacion: 'no se ha devuelto',
},
    {
    ID: '2',
    nombre: 'Josue',
    tipo: 'vaciado',
    peso: 10,
    tamanoAnillo: '5U',
    tamanoPiedra: '1.4mm',
    material: 'plata',
    modelo: '<img src="">',
    detalle: 'anchisimo',
    informacion: 'no se ha devuelto',
},
]
